//RECOVERY EMAIL ACTIONS
export const RECOVERY_EMAIL_START = 'RECOVERY_EMAIL_START';
export const RECOVERY_EMAIL_FAILED = 'RECOVERY_EMAIL_FAILED';
export const RECOVERY_EMAIL_SUCCESS = 'RECOVERY_EMAIL_SUCCESS';

//TOKEN TO RESET THE PASSWORD
export const RECOVERY_TOKEN_SUCCESS = 'RECOVERY_TOKEN_SUCCESS';
export const RECOVERY_TOKEN_FAILED = 'RECOVERY_TOKEN_FAILED';

//RESET PASSWORD
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

//LOGIN
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

//REGISTER
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';