//RECOVERY EMAIL ACTIONS
export const RECOVERY_EMAIL_INIT = 'RECOVERY_EMAIL_INIT';
export const RECOVERY_EMAIL_FAILED = 'RECOVERY_EMAIL_FAILED';
export const RECOVERY_EMAIL_SUCCESS = 'RECOVERY_EMAIL_SUCCESS';