//RECOVERY EMAIL ACTIONS
export const RECOVERY_EMAIL_INIT = 'RECOVERY_EMAIL_INIT';
export const RECOVERY_EMAIL_FAILED = 'RECOVERY_EMAIL_FAILED';
export const RECOVERY_EMAIL_SUCCESS = 'RECOVERY_EMAIL_SUCCESS';

//TOKEN TO RESET THE PASSWORD
export const RECOVERY_TOKEN_CHECK = 'RECOVERY_TOKEN_CHECK';
export const RECOVERY_TOKEN_SUCCESS = 'RECOVERY_TOKEN_SUCCESS';
export const RECOVERY_TOKEN_FAILED = 'RECOVERY_TOKEN_FAILED';

//RESET PASSWORD
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';